Update Package Manager

diff --git a/REQUIRE b/REQUIRE
--- a/REQUIRE
+++ b/REQUIRE
@@ -9,7 +9,7 @@ server_path="https://raw.githubusercontent.com/MRebhan/BashScripts/master/"
 tput bold
 
 if [ "x$(echo $PATH | grep $install_loc)" = "x" ]; then
-  echo Make sure $install_loc is in your path!
+  echo Make sure $install_loc is in your path! >&2
   exit 1
 fi
 install_loc="$install_loc/"
@@ -24,40 +24,40 @@ if [ ! "x$2" = "x" ]; then
         if diff $install_loc.$2 $install_loc$2 > /dev/null; then
           rm $install_loc.$2
         else
-          echo ">>> Updating target: $2"
+          echo ">>> Updating target: $2" >&2
           mv $install_loc.$2 $install_loc$2
           chmod u+x $install_loc$2
         fi
       else
-        echo ">>> Installing target: $2"
+        echo ">>> Installing target: $2" >&2
         mv $install_loc.$2 $install_loc$2
         chmod u+x $install_loc$2
       fi
     else
-      echo ">>> `tput setaf 1`An error occurred while installing $2. Is it a file not downloaded by REQUIRE? If yes, you can ignore this message.`tput sgr0``tput bold`"
+      echo ">>> `tput setaf 1`An error occurred while installing $2. Is it a file that's not in the REQUIRE repository? If yes, you can ignore this message.`tput sgr0``tput bold`" >&2
       rm $install_loc.$2
     fi
   else
-    echo ">>> `tput setaf 1`An error occurred while installing $2.`tput sgr0``tput bold`"
+    echo ">>> `tput setaf 1`An error occurred while installing $2.`tput sgr0``tput bold`" >&2
   fi
 else
-  echo "name is required for SCRIPT mode."
+  echo "name is required for SCRIPT mode." >&2
 fi
 ;;
 "UPDATE")
-echo ">>> Updating all installed scripts..."
+echo ">>> Updating all installed scripts..." >&2
 cd $install_loc
 for file in `ls`; do
   $0 SCRIPT $file
 done
 ;;
 "SELFUPDATE")
-echo ">>> Updating target SELF (REQUIRE)"
+echo ">>> Updating target SELF (REQUIRE)" >&2
 $0 SCRIPT REQUIRE
 ;;
 *)
-echo "Usage: REQUIRE <SCRIPT|SELFUPDATE|UPDATE> [name]"
-echo "REQUIRE is an automatic script updater"
+echo "Usage: REQUIRE <SCRIPT|SELFUPDATE|UPDATE> [name]" >&2
+echo "REQUIRE is an automatic script updater" >&2
 ;;
 esac
 
